# -*- coding: utf-8 -*-
"""LIST

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1djSqRPHkzRq8dJBGoIe6XAQ07n6uVQcg
"""

l=[1,345,45,"sudh",True,5+7j,453,343]

l[5].real

l[0:5:4]

l[0]

l[-1:-5:-2]

l[::2]

l1 = [3,4,5]

l+l1

l1*3

len(l)

l

l1

l.append(l1)

l.extend("sudh")

l.extend([3,4,5])

l1

l1.insert(1,"sudh")

l1

l1.insert(2 , [2,3,4])

l1

l1.insert(-1,45)

l1

l1.insert(0 , 45)

l1

l1.pop()

l1

l1.pop(3)

l1

l1.remove(345)

l1

l1.append(4)

l1

l1.remove(4)

l1

l1

l1

l1=l1[::-1]

l1.reverse()

l2=[45,23,90,0,3,4,5,6,7,8,9]

l2.sort()

l2

l2

t =(2,3,4,5,"sudh", 45.56 ,45+457j ,[3,4,5])

t

type(t)

len(t)

t[0]

t[-1]

t*3

s1 = {}

type(s1)

s2 = {2,3,4,55,6}

type(s2)

s3 ={324,456,"sudh",45+45j ,34.456 ,(3,4,5)}

s3

s3 = {324,456,456,"sudh",45+45j,(3,4,5)}

s3

s4= {2,3,4,5,6,2,2,3,4,5,2,3,1,2,3,4,5,6,1,2,2,3,'sudh','sudh'}

s4

l6 = [2,3,4,5,6,2,2,3,4,5,2,3,1,2,3,4,5,6,1,2,2,3,'sudh','sudh']

l6 = list(set(l6))

l6

s5 = {234,45,23,12,567,45,2,789,234,"abc",456,342,23}

s5

s5

s5.add(4)

s5

s5.remove(2)

s5



d ={}

type(d)

d1 ={'key' :"sudh"}

d1

d2 = {'name':'sudhanshu','eamil':'sudhanshu@123','number':334534}

d2

d2

d3= {234:"sudh", '_wer':"kumar",True:24234}

d3

d3

d3[234]

d3[True]

d4={'name':"sudh",'mail'

marks =int(input("enteryou marks"
if marks >=80
    print(you will be a part of A0 batch")
    elif marks >=60 and marks<80
               print("you will be a part of A1 batch")
               elif marks >=40 and marks<60
               print("you willbe a part of A2 batch")
               else:
               print("you will be a part of A3 batch")

name= input("enter your name")
if(name = ("alok")
couruse=input("enter your courser")

if(course=b.tech)
roll=int('input'("enter your roll no"))
else:
  print(error)
  if(roll=343):
    print("enter 5 marks number:")
    m1=int(input(1))
    m2=int(input(2))
    m3=int(input(3))
    m4=int(input(4))
    m5=int(input(5))

l = [1,2,3,4,4,"sudh", "kumar" , 324,34,456,"abd"]

l1_num =[]
l2_str = []
for i in 1 :
  if type(i) == int or type(i) == float:
    l1_num.append(i)
    else :
      l2_str.append(i)

s = input ("Enter a word:")
if s== s[::-1]:
  print(s, " is a palindrome")
else:
  print(s, " is not a palindrome

from re import X
x=int(input("enter a numbery:") )
temp=X
while x>0:
  digit=x%10
  reverse = (reverse%)+digit
  x=x//10
  if temp>=reverse:
    print(temp,"is a palindrom number")
  else:
    print(temp,"is not a palindrom number

l=[5,9,6,7,8,9,2,3,18,19]
total=0
for 1in 1
total <total>1
print('sum,'total)

"""# New section

# New section
"""

dict1={'a': 'alok','b':'bhuvan','c': 'chandan'}
keys = []
values = []
for itme in dict.itme():
  keys.append(item[0]),vlaues.append(item[1])
  prnit("keys:",keys)
  print("values:",values)

